feat: made travic-ci suitable for go
VladimirBalun/Crashser pull request #1
Opened 2022-09-08 11:33 UTC by srjchsv

feat: made travic-ci suitable for go

Also added makefile with build, test, lint commands

2022-09-08 13:40 UTC, VladimirBalun requested changes

2022-09-08 13:40 UTC, VladimirBalun commented on .travis.yml
> +  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/>
А там тега нет?

2022-09-08 13:40 UTC, VladimirBalun commented on .travis.yml
> +  - cd server && go test -v -race ./...
`./...` ?

2022-09-08 13:40 UTC, VladimirBalun commented on makefile
> +BINARY_NAME=crasher
Обычно название Makefile с большой буквы

2022-09-08 13:40 UTC, VladimirBalun commented on makefile
> +	@go build -o $(BINARY_NAME) cmd/crasher/main.go
Для бинаря лучше сделать отдельную папку и добавить ее в .gitignore

2022-09-08 13:44 UTC, srjchsv commented on .travis.yml
> +  - cd server && go test -v -race ./...
./... это значит во всех директориях тесты запустить.

2022-09-09 06:08 UTC, VladimirBalun commented on Makefile
> +BINARY_NAME=crasher
И давай этот Makefile в папку с сервером, он ведь к серверу относится

2022-09-09 06:12 UTC, VladimirBalun commented on .travis.yml
> +  - cd server && go test -v -race ./...
Ок, буду знать)

2022-09-10 07:40 UTC, VladimirBalun approved these changes

2022-09-10 11:39 UTC, merged