feat: servers dockerfile
VladimirBalun/Crashser pull request #2
Opened 2022-09-08 12:32 UTC by srjchsv

2022-09-08 13:44 UTC, VladimirBalun requested changes

2022-09-08 13:44 UTC, VladimirBalun commented on server/cmd/crasher/main.go
> +	mongodb_repositories "server/internal/app/repositories/mongodb_repository"
К PR не относится

2022-09-08 13:44 UTC, VladimirBalun commented on server/go.mod
>  go 1.19
К PR не относится

2022-09-08 13:44 UTC, VladimirBalun commented on server/dockerfile
> +FROM golang:alpine as builder
Обычно с большой буквы называют Dockerfile

2022-09-08 13:44 UTC, VladimirBalun commented on server/dockerfile
> +FROM golang:alpine as builder
И давай его в папку server перенесем

2022-09-08 13:44 UTC, VladimirBalun commented on server/dockerfile
> +FROM golang:alpine as builder
И давай пустыми линиями разграничим смысловые блоки, чтобы не было все слитно

2022-09-08 15:57 UTC, srjchsv commented on server/cmd/crasher/main.go
> +	mongodb_repositories "server/internal/app/repositories/mongodb_repository"
Согласен, извиняюсь.

2022-09-08 15:57 UTC, srjchsv commented on server/go.mod
>  go 1.19
Согласен, извиняюсь.

2022-09-08 16:01 UTC, srjchsv commented on server/dockerfile
> +FROM golang:alpine as builder
- Сделал с большой буквы.
- В папке сервер он и находиться.
- Разбил на два блока, один собирает, другой бинарь копирует.

2022-09-09 06:09 UTC, VladimirBalun commented on server/cmd/crasher/main.go
> +	mongodb_repositories "server/internal/app/repositories/mongodb_repository"
Все еще есть в PR

2022-09-09 06:09 UTC, VladimirBalun commented on server/go.mod
>  go 1.19
Все еще есть в PR

2022-09-09 06:10 UTC, VladimirBalun commented
Давай переименуем только коммит и PR в `feat: add Dockerfile for server` и перед мержем не забудь посквошить коммиты, т.е. чтобы по этому PR остался один осмысленный коммит

2022-09-09 11:49 UTC, closed without merging