CoreDumpsRepository
VladimirBalun/Crashser pull request #5
Opened 2022-09-13 15:52 UTC by srjchsv

2022-09-13 15:56 UTC, srjchsv commented on server/internal/app/entities/core_dump.go
> +	return c.OsInfo
Пришлось Get везде приставку добавить, а то имена путались так как поля структур нужно импортируемыми сделать

2022-09-13 15:57 UTC, srjchsv commented on server/internal/app/entities/core_dump.go
> +	AppInfo   *AppInfo           `bson:"app_info,omitempty"`
Поля структур пришлось импортируемыми сделать

2022-09-13 15:59 UTC, srjchsv commented on server/internal/app/repositories/mongodb_repository/core_dumps_repository.go
> +	id, err := r.dbClient.InsertOne(context.Background(), coreDump)
решил возврашать еще и  ID, уже сконвертированный в строку

2022-09-13 17:24 UTC, srjchsv commented on server/internal/app/entities/app_info.go
> +func (app *AppInfo) GetVersion() string {
Добавил Get, потомучто поля структуры пришлось импортировать с такими де названиями .

2022-09-13 17:26 UTC, srjchsv commented on server/internal/app/repositories/mongodb_repository/applications_repository.go
> +	for i, v := range res {
Метод возвращял []string, а получение всех документов возвращается []interface{} , здесь в цикле привожу к нужному типу. Или как сделать?

2022-09-13 17:28 UTC, srjchsv commented on server/utils/utils.go
> +		{
Случайные данные генерирую здесь

2022-09-14 13:04 UTC, VladimirBalun commented on server/internal/app/entities/core_dump.go
> +	return c.OsInfo
Предлагаю во всех entities тогда добавить приставку Get

2022-09-14 13:04 UTC, VladimirBalun commented on server/internal/app/entities/core_dump.go
> +	AppInfo   *AppInfo           `bson:"app_info,omitempty"`
Окей

2022-09-14 13:08 UTC, srjchsv commented on server/internal/app/entities/core_dump.go
> +	return c.OsInfo
Так вроде во всех и сделал.

2022-09-14 13:15 UTC, VladimirBalun requested changes

2022-09-14 13:15 UTC, VladimirBalun commented on server/Makefile
> +	@export CRASHER_DATABASE_ADDRESS="mongodb://localhost:27017"
Пока для тестов не будем БД поднимать, нужно ограничиться моками, это когда end-to-end и автотесты будем использовать, тогда и будем поднимать

2022-09-14 13:15 UTC, VladimirBalun commented on server/cmd/crasher/main.go
> +	mongodb_repositories "server/internal/app/repositories/mongodb_repository"
Зачем приставка mongodb_repositories? Почему не mongodb_repository?

2022-09-14 13:15 UTC, VladimirBalun commented on server/cmd/crasher/main.go
> +	mongoDB := dbClient.Database("crasher")
main про базы данных и коллекции знать не должен, он должен знать только про то, какая СУБД используется, а ее детали должны быть инкапсулированы внутри нее

2022-09-14 13:15 UTC, VladimirBalun commented on server/internal/app/repositories/core_dumps_repository.go
> +	AddCoreDump(coreDump entities.CoreDump) (string, error)
А что это за строка возвращаемая в интерфейсе string?

2022-09-14 13:15 UTC, VladimirBalun commented on server/internal/app/repositories/mongodb_repository/applications_repository.go
> +	for i, v := range res {
Да, конечно, здесь нужно приводить к интерфейсу

2022-09-14 13:15 UTC, VladimirBalun commented on server/internal/app/repositories/mongodb_repository/applications_repository_test.go
> +	r := NewApplicationsRepository(db, &zap.Logger{})
Здесь по хрошему db нужно мокать

2022-09-14 13:15 UTC, VladimirBalun commented on server/internal/app/repositories/mongodb_repository/core_dumps_repository.go
> +	id, err := r.dbClient.InsertOne(context.Background(), coreDump)
Нет, возвращать это пока не стоит

2022-09-14 13:15 UTC, VladimirBalun commented on server/internal/app/repositories/mongodb_repository/core_dumps_repository.go
> +	_, err = r.dbClient.DeleteOne(context.Background(), bson.D{{Key: "_id", Value: idHex}})
Давай в конструкторе репозитория передавать таймаут и все запросы в БД делать с этим таймаутом, если запрос выполняется больше таймауту, то будем обрубать его

2022-09-14 13:15 UTC, VladimirBalun commented on server/internal/app/repositories/mongodb_repository/core_dumps_repository.go
>  	return nil
return err - можно упростить

2022-09-14 13:15 UTC, VladimirBalun commented on server/internal/app/repositories/mongodb_repository/core_dumps_repository_test.go
> +	r := NewCoreDumpsRepository(db, &zap.Logger{})
Мокать надо и ниже везде тоже

2022-09-14 13:15 UTC, VladimirBalun commented on server/internal/app/repositories/mongodb_repository/main_test.go
> +package mongodb_repositories
Этого не должно быть, пока должны быть только юнит тесты с моками для каждого репозитория

2022-09-14 13:15 UTC, VladimirBalun commented on server/utils/utils.go
> +		{
Нужно генерировать там, где они необходимы, а не в глобальном пакете

2022-09-14 13:16 UTC, VladimirBalun commented
Давай еще entity CoreDump расширим, чтобы у него был ObjectId

2022-09-14 13:23 UTC, srjchsv commented on server/internal/app/repositories/mongodb_repository/applications_repository.go
> +	for i, v := range res {
Наоборот я слайс типа пустой интерфейс, так монго Distinct метод возвращает данные, по названиям приложений. Перевожу в слайс типа string, в цикле O(n) время и память O(n). Потомучто изначально был сигнатура GetApplicationNames()([]string, error) была такая.

2022-09-14 13:29 UTC, srjchsv commented on server/utils/utils.go
> +		{
ок

2022-09-14 13:33 UTC, srjchsv commented on server/cmd/crasher/main.go
> +	mongodb_repositories "server/internal/app/repositories/mongodb_repository"
У тебя так изначально в ветке develop было mongodb_repositories.

appsRepo := mongodb_repositories.NewApplicationsRepository(db, logger)
coreDumpsRepo := mongodb_repositories.NewCoreDumpsRepository(db, logger)

мой vscode на ctrl+s просто авто импортировал так этот пакет.

2022-09-14 13:35 UTC, srjchsv commented on server/internal/app/repositories/mongodb_repository/applications_repository.go
> +	for i, v := range res {
Наоборот он сейчас слайс типа пустой интерфейс, так монго Distinct метод возвращает данные, по названиям приложений. Перевожу в слайс типа string, в цикле O(n) время и память O(n). Потомучто изначально был сигнатура GetApplicationNames()([]string, error) была такая.

2022-09-14 13:43 UTC, srjchsv commented on server/internal/app/repositories/mongodb_repository/core_dumps_repository.go
> +	_, err = r.dbClient.DeleteOne(context.Background(), bson.D{{Key: "_id", Value: idHex}})
ок

2022-09-14 13:44 UTC, srjchsv commented on server/internal/app/repositories/mongodb_repository/core_dumps_repository.go
>  	return nil
if _, err = r.dbClient.DeleteOne(context.Background(), bson.D{{Key: "_id", Value: idHex}}); err {
		return err
}

так?

2022-09-14 13:46 UTC, srjchsv commented on server/internal/app/repositories/mongodb_repository/core_dumps_repository.go
> +	id, err := r.dbClient.InsertOne(context.Background(), coreDump)
ок

2022-09-14 13:47 UTC, srjchsv commented on server/internal/app/repositories/mongodb_repository/core_dumps_repository_test.go
> +	r := NewCoreDumpsRepository(db, &zap.Logger{})
ок

2022-09-14 13:48 UTC, srjchsv commented on server/internal/app/repositories/core_dumps_repository.go
> +	AddCoreDump(coreDump entities.CoreDump) (string, error)
ID сделанной записи. Может оставить?

2022-09-14 14:05 UTC, srjchsv commented on server/internal/app/repositories/mongodb_repository/main_test.go
> +package mongodb_repositories
ок

2022-09-14 14:11 UTC, srjchsv commented on server/internal/app/repositories/mongodb_repository/applications_repository_test.go
> +	r := NewApplicationsRepository(db, &zap.Logger{})
ок

2022-09-14 17:09 UTC, srjchsv commented on server/cmd/crasher/main.go
> +	mongodb_repositories "server/internal/app/repositories/mongodb_repository"
Вообщем я исправил это тоже

2022-09-14 17:09 UTC, srjchsv commented on server/cmd/crasher/main.go
> +	mongoDB := dbClient.Database("crasher")
ок

2022-09-14 17:16 UTC, srjchsv commented on server/Makefile
> +	@export CRASHER_DATABASE_ADDRESS="mongodb://localhost:27017"
> Давай еще entity CoreDump расширим, чтобы у него был ObjectId

ok

2022-09-14 18:10 UTC, VladimirBalun requested changes

2022-09-14 18:10 UTC, VladimirBalun commented on .travis.yml
> +  - go install github.com/golang/mock/mockgen@v1.6.0
А почему он в go.mod?

2022-09-14 18:10 UTC, VladimirBalun commented on .travis.yml
> +  - make mock
Можно один раз их создать и пусть он лежат в репозитории, чтобы тесты было удобрно локально гонять

2022-09-14 18:10 UTC, VladimirBalun commented on .travis.yml
> +  # - docker pull mongo
Мертвый код удаляем

2022-09-14 18:10 UTC, VladimirBalun commented on .travis.yml
> +# services:
Мертвый код удаляем

2022-09-14 18:10 UTC, VladimirBalun commented on server/Makefile
> +	# @export CRASHER_DATABASE_ADDRESS="mongodb://localhost:27017"
Аналогично

2022-09-14 18:10 UTC, VladimirBalun commented on server/Makefile
> +	# @export CRASHER_DATABASE_ADDRESS="mongodb://localhost:27017"
Аналогично

2022-09-14 18:10 UTC, VladimirBalun commented on server/cmd/crasher/main.go
> +	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
5 лучше вынести в конфигурацию и задавать через переменную окружения

2022-09-14 18:10 UTC, VladimirBalun commented on server/cmd/crasher/main.go
> +	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
В main мы не должны контекст с таймаутом создавать, этот контекст мы должны создавать в репозитории в качестве родителя взяв базовый контекст из контроллера или main-a и брать в качестве таймаута значение из конфигурации

2022-09-14 18:10 UTC, VladimirBalun commented on server/internal/app/entities/app_info.go
> +	Name                string              `bson:"name,omitempty"`
Здесь bson не должны быть никакого? В чистой архитектуре entities описывают только бизнес логику, никаких форматов не должно быть

2022-09-14 18:10 UTC, VladimirBalun commented on server/internal/app/entities/core_dump.go
> +	ID        primitive.ObjectID `bson:"_id,omitempty"`
Аналогично

2022-09-14 18:10 UTC, VladimirBalun commented on server/internal/app/entities/os_info.go
> +	Name         string `bson:"name,omitempty"`
Аналогично

2022-09-14 18:10 UTC, VladimirBalun commented on server/internal/app/repositories/mongodb_repository/applications_repository.go
> +	for i, v := range res {
Нет, это нормально, в чистой архитектуре мы должны использовать простые интерфейсы, чтобы в случае чего было очень просто заменить БД, REST на gRPC и так далее, в случае необходимости

2022-09-14 18:10 UTC, VladimirBalun commented on server/internal/app/repositories/mongodb_repository/applications_repository_test.go
> +			name: "ok",
Еще нужен кейс, на пустой слайс и слайс из одного имени приложения

2022-09-14 18:10 UTC, VladimirBalun commented on server/internal/app/repositories/mongodb_repository/applications_repository_test.go
> +			c := gomock.NewController(t)
Давай выше его создадим, чтобы в цикле это не делать каждый раз

2022-09-14 18:10 UTC, VladimirBalun commented on server/internal/app/repositories/mongodb_repository/applications_repository_test.go
> +			r := mock_repositories.NewMockApplicationsRepository(c)
Аналогично

2022-09-14 18:10 UTC, VladimirBalun commented on server/internal/app/repositories/mongodb_repository/core_dumps_repository.go
>  	return nil
_, err = r.dbClient.DeleteOne(context.Background(), bson.D{{Key: "_id", Value: idHex}})
    return err

2022-09-14 18:10 UTC, VladimirBalun commented on server/internal/app/repositories/mongodb_repository/core_dumps_repository.go
> +	if err != nil {
Тоже здесь можно упростить

2022-09-14 18:10 UTC, VladimirBalun commented on server/internal/app/repositories/mongodb_repository/core_dumps_repository.go
> +	if _, err = r.collection.DeleteOne(r.ctx, bson.D{{Key: "_id", Value: idHex}}); err != nil {
Тоже можно упростить выражение

2022-09-14 18:10 UTC, VladimirBalun commented on server/internal/app/repositories/mongodb_repository/core_dumps_repository_test.go
> +// func addRandomCoreDumpsToDB(quantity int, db *mongo.Collection) error {
Мертвый код не нужен

2022-09-14 18:10 UTC, VladimirBalun commented on server/internal/app/repositories/mongodb_repository/core_dumps_repository_test.go
> +		coreDump := entities.NewCoreDump()
У тебя же есть ф-ия для геренации generateRandomCoreDump - ниже не стоит код дублировать

2022-09-14 18:10 UTC, VladimirBalun commented on server/internal/app/repositories/mongodb_repository/core_dumps_repository_test.go
> +	// NewOSInfo
Комментарии здесь и ниже никакой пользы не несут

2022-09-14 18:10 UTC, VladimirBalun commented on server/internal/app/repositories/mongodb_repository/core_dumps_repository_test.go
> +	osArr = []asInfo{
Глобальные переменные - зло

2022-09-14 18:10 UTC, VladimirBalun commented on server/internal/app/repositories/mongodb_repository/core_dumps_repository_test.go
> +			c := gomock.NewController(t)
Аналогично

2022-09-14 18:10 UTC, VladimirBalun commented on server/internal/app/repositories/mongodb_repository/core_dumps_repository_test.go
> +			r := mock_repositories.NewMockCoreDumpsRepository(c)
Аналогично

2022-09-14 18:10 UTC, VladimirBalun commented on server/internal/app/repositories/mongodb_repository/core_dumps_repository_test.go
> +	}{
Нужен кейс с таймаутом еще

2022-09-14 18:10 UTC, VladimirBalun commented on server/internal/app/repositories/mongodb_repository/core_dumps_repository_test.go
> +	}{
И для applicationRepository тоже

2022-09-14 18:11 UTC, VladimirBalun commented on server/cmd/crasher/main.go
> +	mongodb_repositories "server/internal/app/repositories/mongodb_repository"
Ок, тогда спасибо, я видимо не заметил

2022-09-16 17:41 UTC, VladimirBalun commented
В дискашенах нужно отписываться, что исправил/исправлю или почему не согласен с дискашеном

2022-09-16 17:53 UTC, VladimirBalun requested changes

2022-09-16 17:53 UTC, VladimirBalun commented on server/internal/app/configuration.go
> +	CtxTimeout       = os.Getenv("CTX_TIMEOUT")
Префикс должен иметь вид CRASHER_ и давай его именовать CRASHER_DATABASE_TIMEOUT

2022-09-16 17:53 UTC, VladimirBalun commented on server/internal/app/entities/core_dump.go
> +	ID         primitive.ObjectID `bson:"_id,omitempty"`
bson, как и сказал, в entities не должен быть

2022-09-16 17:53 UTC, VladimirBalun commented on server/internal/app/entities/core_dump.go
> +	Extensions map[string]string  `bson:"extensions"`
Давай лучше слайс пар стрингов

2022-09-16 17:53 UTC, VladimirBalun commented on server/internal/app/entities/query_fields_mongo.go
> +type QueryFieldsMongo struct {
Для options давай такой паттерн использовать: https://golang-blog.blogspot.com/2019/10/functional-options.html

2022-09-16 17:53 UTC, VladimirBalun commented on server/internal/app/repositories/core_dumps_repository.go
> +import (
Почему один импорт в скобках?

2022-09-16 17:53 UTC, VladimirBalun commented on server/internal/app/repositories/mongodb_repository/applications_repository.go
>  func NewApplicationsRepository(db *mongo.Client, l *zap.Logger) *ApplicationsRepository {
Давай еще контекс принимать из main принимать и от него потом будем брать таймаут контекст, чтобы потом был gracefull shutdown

2022-09-16 17:53 UTC, VladimirBalun commented on server/internal/app/repositories/mongodb_repository/applications_repository.go
> +	ctx, cancel := context.WithTimeout(context.Background(), time.Duration(ctxTimeout)*time.Second)
Это будет работать неправильно, этот контекст надо создавать в момент запроса, от контекста, который мы приняли в конструкторе

2022-09-16 17:53 UTC, VladimirBalun commented on server/internal/app/repositories/mongodb_repository/applications_repository.go
> +	// convert []interface to []string
Комментарий лишний и так понятно, что ниже происходит

2022-09-16 17:53 UTC, VladimirBalun commented on server/internal/app/repositories/mongodb_repository/applications_repository.go
> +	strArr := make([]string, len(res))
давай applications назовем

2022-09-16 17:53 UTC, VladimirBalun commented on server/internal/app/repositories/mongodb_repository/core_dumps_repository_test.go
> +		coreDump := entities.NewCoreDump()
Пропустил

2022-09-16 17:53 UTC, VladimirBalun commented on server/internal/app/repositories/mongodb_repository/core_dumps_repository_test.go
> +	}{
Также

2022-09-16 23:31 UTC, srjchsv commented on server/internal/app/entities/app_info.go
> +	Name                string              `bson:"name,omitempty"`
Это нужно чтобы в монго создавать документы, а иначе я не знаю как их сделать.

2022-09-16 23:31 UTC, srjchsv commented on server/internal/app/repositories/mongodb_repository/applications_repository.go
> +	for i, v := range res {
Тогда изменить сигнатуру метода и просто возвращать слайс пустых интерфейсов? Не приводя ответ монго к типу слайс строк? изначально в ветке develop к возврату слайс строк.

2022-09-16 23:31 UTC, srjchsv commented on server/cmd/crasher/main.go
> +	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
перенес в репозиторий

2022-09-16 23:31 UTC, srjchsv commented on server/internal/app/repositories/mongodb_repository/applications_repository_test.go
> +			name: "ok",
сделал

2022-09-16 23:31 UTC, srjchsv commented on server/internal/app/repositories/mongodb_repository/core_dumps_repository_test.go
> +	osArr = []asInfo{
убрал в функцию

2022-09-16 23:31 UTC, srjchsv commented on server/internal/app/repositories/mongodb_repository/applications_repository_test.go
> +			c := gomock.NewController(t)
перенес везде

2022-09-16 23:31 UTC, srjchsv commented on server/internal/app/repositories/mongodb_repository/core_dumps_repository.go
>  	return nil
Ок, сделал спасибо

2022-09-16 23:31 UTC, srjchsv commented on server/internal/app/repositories/mongodb_repository/core_dumps_repository.go
> +	if _, err = r.collection.DeleteOne(r.ctx, bson.D{{Key: "_id", Value: idHex}}); err != nil {
сделал

2022-09-16 23:31 UTC, srjchsv commented on server/internal/app/repositories/mongodb_repository/core_dumps_repository_test.go
> +	}{
не могу понять как его сделать

2022-09-16 23:31 UTC, srjchsv commented on server/internal/app/repositories/mongodb_repository/core_dumps_repository_test.go
> +		coreDump := entities.NewCoreDump()
Оставил одну

2022-09-16 23:31 UTC, srjchsv commented on server/internal/app/repositories/mongodb_repository/core_dumps_repository_test.go
> +	// NewOSInfo
убрал

2022-09-16 23:31 UTC, srjchsv commented on .travis.yml
> +  # - docker pull mongo
удалил

2022-09-16 23:31 UTC, srjchsv commented on .travis.yml
> +# services:
удалил

2022-09-16 23:31 UTC, srjchsv commented on .travis.yml
> +  - make mock
согласен

2022-09-16 23:31 UTC, srjchsv commented on server/internal/app/repositories/mongodb_repository/core_dumps_repository.go
> +	if err != nil {
сделал

2022-09-16 23:31 UTC, srjchsv commented on server/internal/app/repositories/mongodb_repository/applications_repository_test.go
> +			r := mock_repositories.NewMockApplicationsRepository(c)
перенес

2022-09-16 23:31 UTC, srjchsv commented on .travis.yml
> +  - go install github.com/golang/mock/mockgen@v1.6.0
я убрал мок из трэвиса

2022-09-16 23:31 UTC, srjchsv commented on server/internal/app/repositories/mongodb_repository/core_dumps_repository.go
> +		}
Опциональный фильтр по параметрам готов.
И если это вариант подтверждаешь, я по такому же принципу UpdateDump сделаю.

2022-09-16 23:31 UTC, srjchsv commented on server/internal/app/repositories/mongodb_repository/core_dumps_repository.go
> +	_, err := r.collection.DeleteMany(r.ctx, bson.D{})
удаление всех дампов

2022-09-16 23:31 UTC, srjchsv commented on server/internal/app/entities/core_dump.go
> +	Extensions map[string]string  `bson:"extensions"`
Новое поле extensions с key value

2022-09-16 23:31 UTC, srjchsv commented on server/internal/app/entities/core_dump.go
> +	ID         primitive.ObjectID `bson:"_id,omitempty"`
ok

2022-09-16 23:31 UTC, srjchsv commented on server/internal/app/entities/core_dump.go
> +	Extensions map[string]string  `bson:"extensions"`
Как сделать слайс пар стрингов? Слайс структур, с парой полей типа стринг?

2022-09-16 23:31 UTC, srjchsv commented on server/internal/app/entities/query_fields_mongo.go
> +type QueryFieldsMongo struct {
Сделал

2022-09-16 23:31 UTC, srjchsv commented on server/internal/app/repositories/core_dumps_repository.go
> +import (
авто импорт ide

2022-09-16 23:31 UTC, srjchsv commented on server/internal/app/repositories/mongodb_repository/applications_repository.go
>  func NewApplicationsRepository(db *mongo.Client, l *zap.Logger) *ApplicationsRepository {
ok

2022-09-16 23:31 UTC, srjchsv commented on server/internal/app/repositories/mongodb_repository/applications_repository.go
> +	ctx, cancel := context.WithTimeout(context.Background(), time.Duration(ctxTimeout)*time.Second)
Понял) спасибо)

2022-09-16 23:31 UTC, srjchsv commented on server/internal/app/repositories/mongodb_repository/applications_repository.go
> +	// convert []interface to []string
ок

2022-09-16 23:31 UTC, srjchsv commented on server/internal/app/repositories/mongodb_repository/applications_repository.go
> +	strArr := make([]string, len(res))
ok

2022-09-16 23:31 UTC, srjchsv commented on server/internal/app/repositories/mongodb_repository/core_dumps_repository_test.go
> +	}{
Покажи пожалуйста как

2022-09-16 23:31 UTC, srjchsv commented on server/internal/app/repositories/mongodb_repository/core_dumps_repository_test.go
> +		coreDump := entities.NewCoreDump()
Одну же всего оставил. И убрал все в нее вообще, нет глобальных переменных

2022-09-16 23:34 UTC, srjchsv commented on server/internal/app/entities/query_fields_mongo_test.go
> +func Test_QueryFieldsMongo(t *testing.T) {
Тесты на установку опций сделаю как подтвердишь изменения

2022-09-18 12:28 UTC, closed without merging